### ISSUE TITLE
 Could not find patternType 00-atoms-00-atoms. This is a critical error.

### ISSUE THREAD

**Issue by Gregory-Phillips** [pattern-lab/starterkit-mustache-materialdesign#1]
I am getting this critical error when running gulp patternlab:build:
` Could not find patternType 00-atoms-00-atoms. This is a critical error.`
`Trace
    at getPatternSubType (/Users/grphilli/Sites/Pattern-Lab/gulp/edition-node-gulp/node_modules/patternlab-node/core/lib/ui_builder.js:188:15)
    at addPatternSubTypeItem (/Users/grphilli/Sites/Pattern-Lab/gulp/edition-node-gulp/node_modules/patternlab-node/core/lib/ui_builder.js:245:26)
    at /Users/grphilli/Sites/Pattern-Lab/gulp/edition-node-gulp/node_modules/patternlab-node/core/lib/ui_builder.js:369:9
    at arrayEach (/Users/grphilli/Sites/Pattern-Lab/gulp/edition-node-gulp/node_modules/patternlab-node/node_modules/lodash/lodash.js:451:11)
    at Function.forEach (/Users/grphilli/Sites/Pattern-Lab/gulp/edition-node-gulp/node_modules/patternlab-node/node_modules/lodash/lodash.js:8634:14)
    at groupPatterns (/Users/grphilli/Sites/Pattern-Lab/gulp/edition-node-gulp/node_modules/patternlab-node/core/lib/ui_builder.js:333:7)
    at buildFrontend (/Users/grphilli/Sites/Pattern-Lab/gulp/edition-node-gulp/node_modules/patternlab-node/core/lib/ui_builder.js:574:30)
    at Object.buildFrontend (/Users/grphilli/Sites/Pattern-Lab/gulp/edition-node-gulp/node_modules/patternlab-node/core/lib/ui_builder.js:630:7)
    at Object.makePath.build (/Users/grphilli/Sites/Pattern-Lab/gulp/edition-node-gulp/node_modules/patternlab-node/core/lib/patternlab.js:506:16)
    at build (/Users/grphilli/Sites/Pattern-Lab/gulp/edition-node-gulp/gulpfile.js:83:14)`
`[09:41:46] The following tasks did not complete: patternlab:serve, patternlab:build, build`
`[09:41:46] Did you forget to signal async completion?`

**Comment by tonyhaddon** [comment]
More info here: https://github.com/pattern-lab/patternlab-node/issues/436
Seems to be an issue with duplicate folders in the patterns folder:

> Steps to Reproduce
> name two folders _patterns/00-atoms/00-images and _patterns/00-atoms/01-images and build/watch

I had installed a starter kit and then installed a different one. Some duplicate folders were added.

**Comment by SmithersA** [comment]
Is this the expected behavior for atoms-color?
<img width="227" alt="Screen Shot 2019-05-08 at 5 23 51 PM" src="https://user-images.githubusercontent.com/34685983/57409393-2fb6b380-71b6-11e9-8c2a-6325fb6f0a90.png">
